// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBackupJob = "backup_jobs"

// BackupJob mapped from table <backup_jobs>
type BackupJob struct {
	ID           int32     `gorm:"column:id;primaryKey" json:"id"`
	Source       string    `gorm:"column:source" json:"source"`
	Destination  string    `gorm:"column:destination;not null" json:"destination"`
	StartedAt    time.Time `gorm:"column:started_at;not null" json:"started_at"`
	CompletedAt  time.Time `gorm:"column:completed_at" json:"completed_at"`
	TotalFiles   int32     `gorm:"column:total_files;not null" json:"total_files"`
	SuccessCount int32     `gorm:"column:success_count;not null" json:"success_count"`
	FailedCount  int32     `gorm:"column:failed_count;not null" json:"failed_count"`
	SkippedCount int32     `gorm:"column:skipped_count;not null" json:"skipped_count"`
	DurationMs   int32     `gorm:"column:duration_ms;not null" json:"duration_ms"`
	Status       string    `gorm:"column:status;type:TEXT" json:"status"`
}

// TableName BackupJob's table name
func (*BackupJob) TableName() string {
	return TableNameBackupJob
}
