// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFileRecord = "file_records"

// FileRecord mapped from table <file_records>
type FileRecord struct {
	ID          int32     `gorm:"column:id;primaryKey" json:"id"`
	FileName    string    `gorm:"column:file_name;not null" json:"file_name"`
	Path        string    `gorm:"column:path;not null" json:"path"`
	SizeBytes   int32     `gorm:"column:size_bytes;not null" json:"size_bytes"`
	MimeType    string    `gorm:"column:mime_type" json:"mime_type"`
	ModifiedAt  time.Time `gorm:"column:modified_at" json:"modified_at"`
	BackupJobID int32     `gorm:"column:backup_job_id" json:"backup_job_id"`
	Description string    `gorm:"column:description" json:"description"`
	AiStatus    string    `gorm:"column:ai_status;type:TEXT" json:"ai_status"`
	Status      string    `gorm:"column:status;type:TEXT" json:"status"`
	BackupJob   BackupJob `gorm:"foreignKey:BackupJobID;references:ID" json:"backup_job"`
}

// TableName FileRecord's table name
func (*FileRecord) TableName() string {
	return TableNameFileRecord
}
