// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFile(arg1, arg2) {
  return window['go']['service']['DriveService']['DeleteFile'](arg1, arg2);
}

export function GetBackupHistory(arg1) {
  return window['go']['service']['DriveService']['GetBackupHistory'](arg1);
}

export function GetBackupProgress() {
  return window['go']['service']['DriveService']['GetBackupProgress']();
}

export function GetFileMetadata(arg1) {
  return window['go']['service']['DriveService']['GetFileMetadata'](arg1);
}

export function ScanDrive(arg1) {
  return window['go']['service']['DriveService']['ScanDrive'](arg1);
}

export function SetWailsContext(arg1) {
  return window['go']['service']['DriveService']['SetWailsContext'](arg1);
}

export function StartBackup(arg1) {
  return window['go']['service']['DriveService']['StartBackup'](arg1);
}
