// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {backup} from '../models';
import {context} from '../models';

export function DeleteFile(arg1:number,arg2:string):Promise<service.DeleteResult>;

export function GetBackupHistory(arg1:string):Promise<Array<service.BackupJob>>;

export function GetBackupProgress():Promise<service.BackupProgress>;

export function GetFileMetadata(arg1:number):Promise<service.FileMetadata>;

export function ScanDrive(arg1:string):Promise<Array<backup.DriveFile>>;

export function SetWailsContext(arg1:context.Context):Promise<void>;

export function StartBackup(arg1:service.BackupRequest):Promise<service.BackupResult>;
