// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"photo-backup-manager/model/model"
)

func newBackupJob(db *gorm.DB, opts ...gen.DOOption) backupJob {
	_backupJob := backupJob{}

	_backupJob.backupJobDo.UseDB(db, opts...)
	_backupJob.backupJobDo.UseModel(&model.BackupJob{})

	tableName := _backupJob.backupJobDo.TableName()
	_backupJob.ALL = field.NewAsterisk(tableName)
	_backupJob.ID = field.NewInt32(tableName, "id")
	_backupJob.Source = field.NewString(tableName, "source")
	_backupJob.Destination = field.NewString(tableName, "destination")
	_backupJob.StartedAt = field.NewTime(tableName, "started_at")
	_backupJob.CompletedAt = field.NewTime(tableName, "completed_at")
	_backupJob.TotalFiles = field.NewInt32(tableName, "total_files")
	_backupJob.SuccessCount = field.NewInt32(tableName, "success_count")
	_backupJob.FailedCount = field.NewInt32(tableName, "failed_count")
	_backupJob.SkippedCount = field.NewInt32(tableName, "skipped_count")
	_backupJob.DurationMs = field.NewInt32(tableName, "duration_ms")
	_backupJob.Status = field.NewString(tableName, "status")

	_backupJob.fillFieldMap()

	return _backupJob
}

type backupJob struct {
	backupJobDo

	ALL          field.Asterisk
	ID           field.Int32
	Source       field.String
	Destination  field.String
	StartedAt    field.Time
	CompletedAt  field.Time
	TotalFiles   field.Int32
	SuccessCount field.Int32
	FailedCount  field.Int32
	SkippedCount field.Int32
	DurationMs   field.Int32
	Status       field.String

	fieldMap map[string]field.Expr
}

func (b backupJob) Table(newTableName string) *backupJob {
	b.backupJobDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b backupJob) As(alias string) *backupJob {
	b.backupJobDo.DO = *(b.backupJobDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *backupJob) updateTableName(table string) *backupJob {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt32(table, "id")
	b.Source = field.NewString(table, "source")
	b.Destination = field.NewString(table, "destination")
	b.StartedAt = field.NewTime(table, "started_at")
	b.CompletedAt = field.NewTime(table, "completed_at")
	b.TotalFiles = field.NewInt32(table, "total_files")
	b.SuccessCount = field.NewInt32(table, "success_count")
	b.FailedCount = field.NewInt32(table, "failed_count")
	b.SkippedCount = field.NewInt32(table, "skipped_count")
	b.DurationMs = field.NewInt32(table, "duration_ms")
	b.Status = field.NewString(table, "status")

	b.fillFieldMap()

	return b
}

func (b *backupJob) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *backupJob) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 11)
	b.fieldMap["id"] = b.ID
	b.fieldMap["source"] = b.Source
	b.fieldMap["destination"] = b.Destination
	b.fieldMap["started_at"] = b.StartedAt
	b.fieldMap["completed_at"] = b.CompletedAt
	b.fieldMap["total_files"] = b.TotalFiles
	b.fieldMap["success_count"] = b.SuccessCount
	b.fieldMap["failed_count"] = b.FailedCount
	b.fieldMap["skipped_count"] = b.SkippedCount
	b.fieldMap["duration_ms"] = b.DurationMs
	b.fieldMap["status"] = b.Status
}

func (b backupJob) clone(db *gorm.DB) backupJob {
	b.backupJobDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b backupJob) replaceDB(db *gorm.DB) backupJob {
	b.backupJobDo.ReplaceDB(db)
	return b
}

type backupJobDo struct{ gen.DO }

type IBackupJobDo interface {
	gen.SubQuery
	Debug() IBackupJobDo
	WithContext(ctx context.Context) IBackupJobDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBackupJobDo
	WriteDB() IBackupJobDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBackupJobDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBackupJobDo
	Not(conds ...gen.Condition) IBackupJobDo
	Or(conds ...gen.Condition) IBackupJobDo
	Select(conds ...field.Expr) IBackupJobDo
	Where(conds ...gen.Condition) IBackupJobDo
	Order(conds ...field.Expr) IBackupJobDo
	Distinct(cols ...field.Expr) IBackupJobDo
	Omit(cols ...field.Expr) IBackupJobDo
	Join(table schema.Tabler, on ...field.Expr) IBackupJobDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBackupJobDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBackupJobDo
	Group(cols ...field.Expr) IBackupJobDo
	Having(conds ...gen.Condition) IBackupJobDo
	Limit(limit int) IBackupJobDo
	Offset(offset int) IBackupJobDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBackupJobDo
	Unscoped() IBackupJobDo
	Create(values ...*model.BackupJob) error
	CreateInBatches(values []*model.BackupJob, batchSize int) error
	Save(values ...*model.BackupJob) error
	First() (*model.BackupJob, error)
	Take() (*model.BackupJob, error)
	Last() (*model.BackupJob, error)
	Find() ([]*model.BackupJob, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BackupJob, err error)
	FindInBatches(result *[]*model.BackupJob, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BackupJob) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBackupJobDo
	Assign(attrs ...field.AssignExpr) IBackupJobDo
	Joins(fields ...field.RelationField) IBackupJobDo
	Preload(fields ...field.RelationField) IBackupJobDo
	FirstOrInit() (*model.BackupJob, error)
	FirstOrCreate() (*model.BackupJob, error)
	FindByPage(offset int, limit int) (result []*model.BackupJob, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBackupJobDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b backupJobDo) Debug() IBackupJobDo {
	return b.withDO(b.DO.Debug())
}

func (b backupJobDo) WithContext(ctx context.Context) IBackupJobDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b backupJobDo) ReadDB() IBackupJobDo {
	return b.Clauses(dbresolver.Read)
}

func (b backupJobDo) WriteDB() IBackupJobDo {
	return b.Clauses(dbresolver.Write)
}

func (b backupJobDo) Session(config *gorm.Session) IBackupJobDo {
	return b.withDO(b.DO.Session(config))
}

func (b backupJobDo) Clauses(conds ...clause.Expression) IBackupJobDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b backupJobDo) Returning(value interface{}, columns ...string) IBackupJobDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b backupJobDo) Not(conds ...gen.Condition) IBackupJobDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b backupJobDo) Or(conds ...gen.Condition) IBackupJobDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b backupJobDo) Select(conds ...field.Expr) IBackupJobDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b backupJobDo) Where(conds ...gen.Condition) IBackupJobDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b backupJobDo) Order(conds ...field.Expr) IBackupJobDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b backupJobDo) Distinct(cols ...field.Expr) IBackupJobDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b backupJobDo) Omit(cols ...field.Expr) IBackupJobDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b backupJobDo) Join(table schema.Tabler, on ...field.Expr) IBackupJobDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b backupJobDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBackupJobDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b backupJobDo) RightJoin(table schema.Tabler, on ...field.Expr) IBackupJobDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b backupJobDo) Group(cols ...field.Expr) IBackupJobDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b backupJobDo) Having(conds ...gen.Condition) IBackupJobDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b backupJobDo) Limit(limit int) IBackupJobDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b backupJobDo) Offset(offset int) IBackupJobDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b backupJobDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBackupJobDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b backupJobDo) Unscoped() IBackupJobDo {
	return b.withDO(b.DO.Unscoped())
}

func (b backupJobDo) Create(values ...*model.BackupJob) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b backupJobDo) CreateInBatches(values []*model.BackupJob, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b backupJobDo) Save(values ...*model.BackupJob) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b backupJobDo) First() (*model.BackupJob, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BackupJob), nil
	}
}

func (b backupJobDo) Take() (*model.BackupJob, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BackupJob), nil
	}
}

func (b backupJobDo) Last() (*model.BackupJob, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BackupJob), nil
	}
}

func (b backupJobDo) Find() ([]*model.BackupJob, error) {
	result, err := b.DO.Find()
	return result.([]*model.BackupJob), err
}

func (b backupJobDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BackupJob, err error) {
	buf := make([]*model.BackupJob, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b backupJobDo) FindInBatches(result *[]*model.BackupJob, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b backupJobDo) Attrs(attrs ...field.AssignExpr) IBackupJobDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b backupJobDo) Assign(attrs ...field.AssignExpr) IBackupJobDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b backupJobDo) Joins(fields ...field.RelationField) IBackupJobDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b backupJobDo) Preload(fields ...field.RelationField) IBackupJobDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b backupJobDo) FirstOrInit() (*model.BackupJob, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BackupJob), nil
	}
}

func (b backupJobDo) FirstOrCreate() (*model.BackupJob, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BackupJob), nil
	}
}

func (b backupJobDo) FindByPage(offset int, limit int) (result []*model.BackupJob, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b backupJobDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b backupJobDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b backupJobDo) Delete(models ...*model.BackupJob) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *backupJobDo) withDO(do gen.Dao) *backupJobDo {
	b.DO = *do.(*gen.DO)
	return b
}
